const bcrypt = require('bcryptjs');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const hashedPassword = await bcrypt.hash('password123', 10);
    
    const users = [
      // LGU-PMT Users
      {
        id: '550e8400-e29b-41d4-a716-446655440001',
        name: 'Mayor John Santos',
        username: 'mayor.santos',
        email: 'mayor.santos@santacruz.gov.ph',
        password: hashedPassword,
        role: 'LGU-PMT',
        sub_role: 'Chair',
        status: 'active',
        id_type: 'Government ID',
        id_number: 'GOV-001',
        group: 'Local Government Unit',
        department: 'Office of the Mayor',
        position: 'Municipal Mayor',
        contact_number: '+63 912 345 6789',
        address: 'Municipal Hall, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440002',
        name: 'Vice Mayor Maria Garcia',
        username: 'vice.mayor.garcia',
        email: 'vice.mayor.garcia@santacruz.gov.ph',
        password: hashedPassword,
        role: 'LGU-PMT',
        sub_role: 'Vice Chair',
        status: 'active',
        id_type: 'Government ID',
        id_number: 'GOV-002',
        group: 'Local Government Unit',
        department: 'Office of the Vice Mayor',
        position: 'Municipal Vice Mayor',
        contact_number: '+63 912 345 6790',
        address: 'Municipal Hall, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440003',
        name: 'Engr. Roberto Cruz',
        username: 'engr.cruz',
        email: 'engr.cruz@santacruz.gov.ph',
        password: hashedPassword,
        role: 'LGU-PMT',
        sub_role: 'Secretariat',
        status: 'active',
        id_type: 'Government ID',
        id_number: 'GOV-003',
        group: 'Local Government Unit',
        department: 'Municipal Engineering Office',
        position: 'Municipal Engineer',
        contact_number: '+63 912 345 6791',
        address: 'Municipal Hall, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },

      // EIU Users
      {
        id: '550e8400-e29b-41d4-a716-446655440004',
        name: 'Atty. Ana Reyes',
        username: 'atty.reyes',
        email: 'atty.reyes@eiu.gov.ph',
        password: hashedPassword,
        role: 'EIU',
        sub_role: 'EPIU Manager',
        status: 'active',
        id_type: 'Government ID',
        id_number: 'EIU-001',
        group: 'External Implementing Unit',
        department: 'Department of Public Works and Highways',
        position: 'EPIU Manager',
        contact_number: '+63 912 345 6792',
        address: 'DPWH Regional Office, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440005',
        name: 'Engr. Carlos Mendoza',
        username: 'engr.mendoza',
        email: 'engr.mendoza@eiu.gov.ph',
        password: hashedPassword,
        role: 'EIU',
        sub_role: 'EPIU Staff',
        status: 'active',
        id_type: 'Government ID',
        id_number: 'EIU-002',
        group: 'External Implementing Unit',
        department: 'Department of Public Works and Highways',
        position: 'Project Engineer',
        contact_number: '+63 912 345 6793',
        address: 'DPWH Regional Office, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },

      // LGU-IU Users
      {
        id: '550e8400-e29b-41d4-a716-446655440006',
        name: 'Dr. Elena Torres',
        username: 'dr.torres',
        email: 'dr.torres@santacruz.gov.ph',
        password: hashedPassword,
        role: 'LGU-IU',
        sub_role: 'MDC Chair',
        status: 'active',
        id_type: 'Government ID',
        id_number: 'LGU-001',
        group: 'Local Government Unit',
        department: 'Municipal Development Council',
        position: 'MDC Chairperson',
        contact_number: '+63 912 345 6794',
        address: 'Municipal Hall, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440007',
        name: 'Mr. Jose Martinez',
        username: 'jose.martinez',
        email: 'jose.martinez@santacruz.gov.ph',
        password: hashedPassword,
        role: 'LGU-IU',
        sub_role: 'Oversight Officer',
        status: 'active',
        id_type: 'Government ID',
        id_number: 'LGU-002',
        group: 'Local Government Unit',
        department: 'Municipal Planning and Development Office',
        position: 'Oversight Officer',
        contact_number: '+63 912 345 6795',
        address: 'Municipal Hall, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440008',
        name: 'Ms. Sofia Rodriguez',
        username: 'sofia.rodriguez',
        email: 'sofia.rodriguez@santacruz.gov.ph',
        password: hashedPassword,
        role: 'LGU-IU',
        sub_role: 'Implementing Staff',
        status: 'active',
        id_type: 'Government ID',
        id_number: 'LGU-003',
        group: 'Local Government Unit',
        department: 'Municipal Engineering Office',
        position: 'Project Coordinator',
        contact_number: '+63 912 345 6796',
        address: 'Municipal Hall, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },

      // EMS Users
      {
        id: '550e8400-e29b-41d4-a716-446655440009',
        name: 'Ms. Patricia Lopez',
        username: 'patricia.lopez',
        email: 'patricia.lopez@ngo.org.ph',
        password: hashedPassword,
        role: 'EMS',
        sub_role: 'NGO Representative',
        status: 'active',
        id_type: 'NGO ID',
        id_number: 'NGO-001',
        group: 'Non-Government Organization',
        department: 'Community Development Foundation',
        position: 'Executive Director',
        contact_number: '+63 912 345 6797',
        address: 'Community Center, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440010',
        name: 'Mr. Ricardo Santos',
        username: 'ricardo.santos',
        email: 'ricardo.santos@cso.org.ph',
        password: hashedPassword,
        role: 'EMS',
        sub_role: 'CSO Member',
        status: 'active',
        id_type: 'CSO ID',
        id_number: 'CSO-001',
        group: 'Civil Society Organization',
        department: 'Citizens Action Group',
        position: 'Community Leader',
        contact_number: '+63 912 345 6798',
        address: 'Barangay Hall, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440011',
        name: 'Engr. Manuel Aquino',
        username: 'manuel.aquino',
        email: 'manuel.aquino@ppmc.gov.ph',
        password: hashedPassword,
        role: 'EMS',
        sub_role: 'PPMC Representative',
        status: 'active',
        id_type: 'Government ID',
        id_number: 'PPMC-001',
        group: 'Provincial Project Monitoring Committee',
        department: 'Provincial Planning and Development Office',
        position: 'PPMC Representative',
        contact_number: '+63 912 345 6799',
        address: 'Provincial Capitol, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },

      // SYS.AD Users
      {
        id: '550e8400-e29b-41d4-a716-446655440012',
        name: 'System Administrator',
        username: 'sysadmin',
        email: 'santacruzadmin@gmail.com',
        password: await bcrypt.hash('BuildWatch', 10),
        role: 'SYS.AD',
        sub_role: 'System Administrator',
        status: 'active',
        id_type: 'System ID',
        id_number: 'SYS-001',
        group: 'System Administration',
        department: 'Information Technology',
        position: 'System Administrator',
        contact_number: '+63 912 345 6800',
        address: 'Municipal Hall, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440013',
        name: 'Executive Admin',
        username: 'executive.admin',
        email: 'executive.admin@buildwatch.gov.ph',
        password: hashedPassword,
        role: 'SYS.AD',
        sub_role: 'Executive',
        status: 'active',
        id_type: 'System ID',
        id_number: 'SYS-002',
        group: 'System Administration',
        department: 'Executive Office',
        position: 'Executive Administrator',
        contact_number: '+63 912 345 6801',
        address: 'Municipal Hall, Santa Cruz, Laguna',
        created_at: new Date(),
        updated_at: new Date()
      }
    ];

    await queryInterface.bulkInsert('users', users, {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('users', null, {});
  }
}; 